# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: bittware
      url-base: https://github.com/matthew-morgan-molex
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: bsim
      repo-path: babblesim-manifest
      revision: 908ffde6298a937c6549dbfa843a62caab26bfc5
      path: tools/bsim
      groups:
        - babblesim
    - name: babblesim_base
      remote: babblesim
      repo-path: base.git
      path: tools/bsim/components
      revision: 02838ca04c4562e68dc876196828d8121679e537
      groups:
        - babblesim
    - name: babblesim_ext_2G4_libPhyComv1
      remote: babblesim
      repo-path: ext_2G4_libPhyComv1.git
      path: tools/bsim/components/ext_2G4_libPhyComv1
      revision: 9018113a362fa6c9e8f4b9cab9e5a8f12cc46b94
      groups:
        - babblesim
    - name: babblesim_ext_2G4_phy_v1
      remote: babblesim
      repo-path: ext_2G4_phy_v1.git
      path: tools/bsim/components/ext_2G4_phy_v1
      revision: cf2d86e736efac4f12fad5093ed2da2c5b406156
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_NtNcable
      remote: babblesim
      repo-path: ext_2G4_channel_NtNcable.git
      path: tools/bsim/components/ext_2G4_channel_NtNcable
      revision: 20a38c997f507b0aa53817aab3d73a462fff7af1
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_multiatt
      remote: babblesim
      repo-path: ext_2G4_channel_multiatt.git
      path: tools/bsim/components/ext_2G4_channel_multiatt
      revision: e09bc2d14b1975f969ad19c6ed23eb20e5dc3d09
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_magic
      remote: babblesim
      repo-path: ext_2G4_modem_magic.git
      path: tools/bsim/components/ext_2G4_modem_magic
      revision: cb70771794f0bf6f262aa474848611c68ae8f1ed
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_BLE_simple
      remote: babblesim
      repo-path: ext_2G4_modem_BLE_simple.git
      path: tools/bsim/components/ext_2G4_modem_BLE_simple
      revision: ce975a3259fd0dd761d371b60435242d54794bad
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_burst_interferer
      remote: babblesim
      repo-path: ext_2G4_device_burst_interferer.git
      path: tools/bsim/components/ext_2G4_device_burst_interferer
      revision: 5b5339351d6e6a2368c686c734dc8b2fc65698fc
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_WLAN_actmod
      remote: babblesim
      repo-path: ext_2G4_device_WLAN_actmod.git
      path: tools/bsim/components/ext_2G4_device_WLAN_actmod
      revision: 9cb6d8e72695f6b785e57443f0629a18069d6ce4
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_playback
      remote: babblesim
      repo-path: ext_2G4_device_playback.git
      path: tools/bsim/components/ext_2G4_device_playback
      revision: 85c645929cf1ce995d8537107d9dcbd12ed64036
      groups:
        - babblesim
    - name: babblesim_ext_libCryptov1
      remote: babblesim
      repo-path: ext_libCryptov1.git
      path: tools/bsim/components/ext_libCryptov1
      revision: eed6d7038e839153e340bd333bc43541cb90ba64
      groups:
        - babblesim
    - name: canopennode
      revision: dec12fa3f0d790cafa8414a4c2930ea71ab72ffd
      path: modules/lib/canopennode
    - name: chre
      revision: b7955c27e50485b7dafdc3888d7d6afdc2ac6d96
      path: modules/lib/chre
    - name: cmsis
      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3
      path: modules/hal/cmsis
      groups:
        - hal
    - name: edtt
      revision: 64e5105ad82390164fb73fc654be3f73a608209a
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_nxp
      remote: bittware
      revision: 4ba45e0e2657ec314116125ebd750c8f6dc219bb
      path: modules/hal/nxp
      groups:
        - hal
    - name: liblc3
      revision: 448f3de31f49a838988a162ef1e23a89ddf2d2ed
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
    - name: loramac-node
      revision: ce57712f3e426bbbb13acaec97b45369f716f43a
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 7102083f626cda09e5792420ea60af0525cce9ae
      path: modules/lib/gui/lvgl
    - name: lz4
      revision: 8e303c264fc21c2116dc612658003a22e933124d
      path: modules/lib/lz4
    - name: mbedtls
      revision: 6e7841e5a08eb5da3c82dbc8b6b6d82ae4b7d2a0
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      remote: bittware
      revision: 064a62b06989ca31d1be1d7bd927fcdcd1db4468
      path: bootloader/mcuboot
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: 0d521d8055f3b2b4842f728b0365d3f0ece9c37f
    - name: nanopb
      revision: 42fa8b211e946b90b9d968523fce7b1cfe27617e
      path: modules/lib/nanopb
    - name: net-tools
      revision: e0828aa9629b533644dc96ff6d1295c939bd713c
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: c8d2ecd25d6976d2d77eccf66878420fdb8ef5a1
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      revision: c904a01d4a882bcbb39987e0e2ce5308f49ac7ad
      path: modules/lib/open-amp
    - name: openthread
      revision: d9abe3071c0131a4adb5d7e7451319b735e6d855
      path: modules/lib/openthread
    - name: picolibc
      path: modules/lib/picolibc
      revision: d07c38ff051386f8e09a143ea0a6c1d6d66dd1d8
    - name: segger
      revision: 4bfaf28a11c3e5ec29badac744fab6d2f342749e
      path: modules/debug/segger
      groups:
        - debug
    - name: sof
      revision: ffbf9c2a6ea2930b0ac7e3a37c7cd7f5c417d090
      path: modules/audio/sof
    - name: tflite-micro
      revision: 9156d050927012da87079064db59d07f03b8baf6
      path: modules/lib/tflite-micro
      repo-path: tflite-micro
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: TraceRecorderSource
      revision: bc839bf94904bcdb91b33760e918afbef82e3ab4
      path: modules/debug/TraceRecorder
      groups:
        - debug
    - name: trusted-firmware-m
      revision: 79a6115d3a8d0e04864ae8156c1dc8532b750f5a
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: trusted-firmware-a
      revision: 28f5e137837f1c1a7a7b2af2dd8bb778c0a27532
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: tf-m-tests
      revision: 0f80a65193ddbbe3f0ac38b33b07b26138c11fa7
      path: modules/tee/tf-m/tf-m-tests
      groups:
        - tee
    - name: psa-arch-tests
      revision: 6a17330e0dfb5f319730f974d5b05f7b7f04757b
      path: modules/tee/tf-m/psa-arch-tests
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: e8920192b66db4f909eb9cd3f155d5245c1ae825
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: 67fd8bb88d3136738661fa8bb5f9989103f4599e
      path: modules/lib/zcbor
    - name: zscilib
      path: modules/lib/zscilib
      revision: 34c3432e81085bb717e4871d21ca419ae0058ec5
    - name: thrift
      path: modules/lib/thrift
      revision: 10023645a0e6cb7ce23fcd7fd3dbac9f18df6234

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
